# debug options for the developer;

$G_DATA->{CONSTANTS}->{DOWNLOADMETHODS}->{lwp}      = 'lwp';
$G_DATA->{CONSTANTS}->{DOWNLOADMETHODS}->{httpTiny} = 'httpTiny';
$G_DATA->{CONSTANTS}->{DOWNLOADMETHODS}->{wwwMech}  = 'wwwMech';

$G_DATA->{downloadMethod} = $G_DATA->{CONSTANTS}->{DOWNLOADMETHODS}->{wwwMech};

$G_DATA->{sendMail}                           = 1;
$G_DATA->{G_WAIT_BETWEEN_FULL_PROCESS_IN_SEC} = 8 * 60;

$G_DATA->{silentHours}->{from} = 20;
$G_DATA->{silentHours}->{till} = 06;

# FIXME: debug
$G_DATA->{mailRecipients} = [ '"Sanyi" <berczi.sandor@gmail.com>' ];
$G_DATA->{mailRecipients} = [ '"Sanyi" <berczi.sandor@gmail.com>', '"Tillatilla1966" <tillatilla.1966@gmail.com>' ];

$G_DATA->{AUTOSCOUT}->{XPATHS}->{XPATH_TALALATI_LISTA} = '//div[contains(concat(" ", @class, " "), " cl-list-element cl-list-element-gap ")]';
$G_DATA->{AUTOSCOUT}->{XPATHS}->{XPATH_TITLE}          = './/h2[contains(concat(" ", @class, " "), " cldt-summary-makemodel ")]';
$G_DATA->{AUTOSCOUT}->{XPATHS}->{XPATH_TITLE2}         = './/h2[contains(concat(" ", @class, " "), " cldt-summary-version ")]';
$G_DATA->{AUTOSCOUT}->{XPATHS}->{XPATH_DESC}           = './/h3[contains(concat(" ", @class, " "), " cldt-summary-subheadline ")]';
$G_DATA->{AUTOSCOUT}->{XPATHS}->{XPATH_LINK}           = './/div[contains(concat(" ", @class, " "), " cldt-summary-titles ")]/a/@href';
$G_DATA->{AUTOSCOUT}->{XPATHS}->{XPATH_PRICE}          = './/span[contains(concat(" ", @class, " "), " cldt-price ")]';
$G_DATA->{AUTOSCOUT}->{XPATHS}->{XPATH_FEATURES}       = './/div[contains(concat(" ", @class, " "), " cldt-summary-vehicle-data ")]/ul/li';
$G_DATA->{AUTOSCOUT}->{textToDelete}
  = 'Weitere Informationen zum offiziellen Kraftstoffverbrauch und den offiziellen spezifischen CO2-Emissionen neuer Personenkraftwagen können dem "Leitfaden über den Kraftstoffverbrauch, die CO2-Emissionen und den Stromverbrauch neuer Personenkraftwagen" entnommen werden, der an allen Verkaufsstellen und bei der Deutschen Automobil Treuhand GmbH unter www.dat.at unentgeltlich erhältlich ist.';

# mmvmk0=9&mmvco=1&fregfrom=2013&fregto=2015&pricefrom=0&priceto=8000&fuel=B&kmfrom=10000&powertype=kw&atype=C&ustate=N%2CU&sort=standard&desc=0

# ustate=N%2CU&     N,U: nem balesetes; A: balesetes;
$G_DATA->{AUTOSCOUT}->{searchConfig}->{defaults}->{pricefrom} = 500;
$G_DATA->{AUTOSCOUT}->{searchConfig}->{defaults}->{priceto}   = 6000;
$G_DATA->{AUTOSCOUT}->{searchConfig}->{defaults}->{sort}      = 'age';
$G_DATA->{AUTOSCOUT}->{searchConfig}->{defaults}->{desc}      = 0;
$G_DATA->{AUTOSCOUT}->{searchConfig}->{defaults}->{cy}        = 'A,D';    # A: Austria; D: Germany
$G_DATA->{AUTOSCOUT}->{searchConfig}->{defaults}->{offer}
  = 'D,J,O,S,U';    # D: Vorführfahrzeug, J: Jahreswagen, N: Neu, O: Oldtimer, S: Tageszulassung, U: Gebraucht
$G_DATA->{AUTOSCOUT}->{searchConfig}->{defaults}->{mmvco}     = 1;
$G_DATA->{AUTOSCOUT}->{searchConfig}->{defaults}->{powertype} = 'kw';
$G_DATA->{AUTOSCOUT}->{searchConfig}->{defaults}->{atype}     = 'C';
$G_DATA->{AUTOSCOUT}->{searchConfig}->{defaults}->{ustate}    = 'A,N,U';      #  A: balesetes; N,U: nem balesetes;
$G_DATA->{AUTOSCOUT}->{searchConfig}->{defaults}->{page}      = "VVPAGEVV";
$G_DATA->{AUTOSCOUT}->{searchConfig}->{defaults}->{size}      = 20;           # size per page

$G_DATA->{AUTOSCOUT}->{searchConfig}->{mmvmk0}->{Audi}->{maxAge}       = 11;
$G_DATA->{AUTOSCOUT}->{searchConfig}->{mmvmk0}->{Citroen}->{maxAge}    = 11;
$G_DATA->{AUTOSCOUT}->{searchConfig}->{mmvmk0}->{Fiat}->{maxAge}       = 11;
$G_DATA->{AUTOSCOUT}->{searchConfig}->{mmvmk0}->{Ford}->{maxAge}       = 11;
$G_DATA->{AUTOSCOUT}->{searchConfig}->{mmvmk0}->{Honda}->{maxAge}      = 11;
$G_DATA->{AUTOSCOUT}->{searchConfig}->{mmvmk0}->{Hyundai}->{maxAge}    = 11;
$G_DATA->{AUTOSCOUT}->{searchConfig}->{mmvmk0}->{Opel}->{maxAge}       = 11;
$G_DATA->{AUTOSCOUT}->{searchConfig}->{mmvmk0}->{SEAT}->{maxAge}       = 11;
$G_DATA->{AUTOSCOUT}->{searchConfig}->{mmvmk0}->{Skoda}->{maxAge}      = 11;
$G_DATA->{AUTOSCOUT}->{searchConfig}->{mmvmk0}->{Toyota}->{maxAge}     = 11;
$G_DATA->{AUTOSCOUT}->{searchConfig}->{mmvmk0}->{Volkswagen}->{maxAge} = 11;

my %MAKERS = (
  "Audi"              => 9,
  "BMW"               => 13,
  "Ford"              => 29,
  "Mercedes-Benz"     => 47,
  "Opel"              => 54,
  "Volkswagen"        => 74,
  "Abarth"            => 16396,
  "AC"                => 14979,
  "ACM"               => 16429,
  "Acura"             => 16356,
  "Aixam"             => 16352,
  "Alfa Romeo"        => 6,
  "Alpina"            => 14,
  "Amphicar"          => 51545,
  "Ariel"             => 16419,
  "Artega"            => 16427,
  "Aspid"             => 16431,
  "Aston Martin"      => 8,
  "Austin"            => 15643,
  "Autobianchi"       => 15644,
  "Auverland"         => 16437,
  "Baic"              => 51774,
  "Bedford"           => 16400,
  "Bellier"           => 16416,
  "Bentley"           => 11,
  "Bollore"           => 16418,
  "Borgward"          => 16424,
  "Brilliance"        => 16367,
  "Bugatti"           => 15,
  "Buick"             => 16,
  "BYD"               => 16379,
  "Cadillac"          => 17,
  "Caravans-Wohnm"    => 15672,
  "Casalini"          => 16407,
  "Caterham"          => 16335,
  "Changhe"           => 16401,
  "Chatenet"          => 16357,
  "Chery"             => 16384,
  "Chevrolet"         => 19,
  "Chrysler"          => 20,
  "Citroen"           => 21,
  "CityEL"            => 16411,
  "CMC"               => 16406,
  "Corvette"          => 16380,
  "Courb"             => 51558,
  "Dacia"             => 16360,
  "Daewoo"            => 22,
  "DAF"               => 16333,
  "Daihatsu"          => 23,
  "Daimler"           => 16397,
  "Dangel"            => 16434,
  "De la Chapelle"    => 16423,
  "De Tomaso"         => 51779,
  "Derways"           => 16391,
  "DFSK"              => 51773,
  "Dodge"             => 2152,
  "Donkervoort"       => 16339,
  "DR Motor"          => 16383,
  "DS Automobiles"    => 16415,
  "Dutton"            => 51552,
  "Estrima"           => 16436,
  "Ferrari"           => 27,
  "Fiat"              => 28,
  "FISKER"            => 51543,
  "Gac Gonow"         => 51542,
  "Galloper"          => 16337,
  "GAZ"               => 16386,
  "Geely"             => 16392,
  "GEM"               => 16403,
  "GEMBALLA"          => 51540,
  "Giotti Victoria"   => 16421,
  "GMC"               => 2153,
  "Great Wall"        => 16382,
  "Grecav"            => 16409,
  "Haima"             => 51512,
  "Hamann"            => 51534,
  "Honda"             => 31,
  "HUMMER"            => 15674,
  "Hurtan"            => 51767,
  "Hyundai"           => 33,
  "Infiniti"          => 16355,
  "Innocenti"         => 15629,
  "Iso Rivolta"       => 16402,
  "Isuzu"             => 35,
  "Iveco"             => 14882,
  "IZH"               => 16387,
  "Jaguar"            => 37,
  "Jeep"              => 38,
  "Karabag"           => 16417,
  "Kia"               => 39,
  "Koenigsegg"        => 51781,
  "KTM"               => 50060,
  "Lada"              => 40,
  "Lamborghini"       => 41,
  "Lancia"            => 42,
  "Land Rover"        => 15641,
  "LDV"               => 16426,
  "Lexus"             => 43,
  "Lifan"             => 16393,
  "Ligier"            => 16353,
  "Lincoln"           => 14890,
  "Lotus"             => 44,
  "Mahindra"          => 16359,
  "MAN"               => 51780,
  "Mansory"           => 16435,
  "Martin Motors"     => 16410,
  "Maserati"          => 45,
  "Maybach"           => 16348,
  "Mazda"             => 46,
  "McLaren"           => 51519,
  "Melex"             => 16399,
  "MG"                => 48,
  "Microcar"          => 16361,
  "Minauto"           => 51766,
  "MINI"              => 16338,
  "Mitsubishi"        => 50,
  "Mitsuoka"          => 51782,
  "Morgan"            => 51,
  "Moskvich"          => 16388,
  "MP Lafer"          => 51554,
  "Nissan"            => 52,
  "Oldsmobile"        => 53,
  "Oldtimer"          => 15670,
  "Pagani"            => 16341,
  "Panther Westwinds" => 51553,
  "Peugeot"           => 55,
  "PGO"               => 50083,
  "Piaggio"           => 16350,
  "Plymouth"          => 51770,
  "Pontiac"           => 56,
  "Porsche"           => 57,
  "Proton"            => 15636,
  "Puch"              => 51768,
  "Qoros"             => 16412,
  "Qvale"             => 16425,
  "Reliant"           => 16398,
  "Renault"           => 60,
  "Rolls-Royce"       => 61,
  "Rover"             => 62,
  "Ruf"               => 51536,
  "Saab"              => 63,
  "Santana"           => 16369,
  "Savel"             => 16405,
  "SDG"               => 51771,
  "SEAT"              => 64,
  "Skoda"             => 65,
  "smart"             => 15525,
  "SpeedArt"          => 51538,
  "Spyker"            => 16377,
  "SsangYong"         => 66,
  "Subaru"            => 67,
  "Suzuki"            => 68,
  "TagAZ"             => 16395,
  "Talbot"            => 51551,
  "Tasso"             => 16404,
  "Tata"              => 16327,
  "Tazzari EV"        => 51557,
  "TECHART"           => 51535,
  "Tesla"             => 51520,
  "Town Life"         => 16420,
  "Toyota"            => 70,
  "Trabant"           => 15633,
  "Trailer-Anhaenger" => 16326,
  "Triumph"           => 2120,
  "Trucks-Lkw"        => 16253,
  "TVR"               => 71,
  "UAZ"               => 16389,
  "VAZ"               => 16385,
  "VEM"               => 16422,
  "Volvo"             => 73,
  "Vortex"            => 51514,
  "Wallys"            => 51776,
  "Wartburg"          => 16336,
  "Westfield"         => 51513,
  "Wiesmann"          => 16351,
  "Zastava"           => 16408,
  "ZAZ"               => 16394,
  "Sonstige"          => 16328,
);

# $G_DATA->{AUTOSCOUT}->{makers} = %MAKERS;

$G_DATA->{AUTOSCOUT}->{makers}->{"Audi"}              = 9;
$G_DATA->{AUTOSCOUT}->{makers}->{"BMW"}               = 13;
$G_DATA->{AUTOSCOUT}->{makers}->{"Ford"}              = 29;
$G_DATA->{AUTOSCOUT}->{makers}->{"Mercedes-Benz"}     = 47;
$G_DATA->{AUTOSCOUT}->{makers}->{"Opel"}              = 54;
$G_DATA->{AUTOSCOUT}->{makers}->{"Volkswagen"}        = 74;
$G_DATA->{AUTOSCOUT}->{makers}->{"Abarth"}            = 16396;
$G_DATA->{AUTOSCOUT}->{makers}->{"AC"}                = 14979;
$G_DATA->{AUTOSCOUT}->{makers}->{"ACM"}               = 16429;
$G_DATA->{AUTOSCOUT}->{makers}->{"Acura"}             = 16356;
$G_DATA->{AUTOSCOUT}->{makers}->{"Aixam"}             = 16352;
$G_DATA->{AUTOSCOUT}->{makers}->{"Alfa Romeo"}        = 6;
$G_DATA->{AUTOSCOUT}->{makers}->{"Alpina"}            = 14;
$G_DATA->{AUTOSCOUT}->{makers}->{"Amphicar"}          = 51545;
$G_DATA->{AUTOSCOUT}->{makers}->{"Ariel"}             = 16419;
$G_DATA->{AUTOSCOUT}->{makers}->{"Artega"}            = 16427;
$G_DATA->{AUTOSCOUT}->{makers}->{"Aspid"}             = 16431;
$G_DATA->{AUTOSCOUT}->{makers}->{"Aston Martin"}      = 8;
$G_DATA->{AUTOSCOUT}->{makers}->{"Austin"}            = 15643;
$G_DATA->{AUTOSCOUT}->{makers}->{"Autobianchi"}       = 15644;
$G_DATA->{AUTOSCOUT}->{makers}->{"Auverland"}         = 16437;
$G_DATA->{AUTOSCOUT}->{makers}->{"Baic"}              = 51774;
$G_DATA->{AUTOSCOUT}->{makers}->{"Bedford"}           = 16400;
$G_DATA->{AUTOSCOUT}->{makers}->{"Bellier"}           = 16416;
$G_DATA->{AUTOSCOUT}->{makers}->{"Bentley"}           = 11;
$G_DATA->{AUTOSCOUT}->{makers}->{"Bollore"}           = 16418;
$G_DATA->{AUTOSCOUT}->{makers}->{"Borgward"}          = 16424;
$G_DATA->{AUTOSCOUT}->{makers}->{"Brilliance"}        = 16367;
$G_DATA->{AUTOSCOUT}->{makers}->{"Bugatti"}           = 15;
$G_DATA->{AUTOSCOUT}->{makers}->{"Buick"}             = 16;
$G_DATA->{AUTOSCOUT}->{makers}->{"BYD"}               = 16379;
$G_DATA->{AUTOSCOUT}->{makers}->{"Cadillac"}          = 17;
$G_DATA->{AUTOSCOUT}->{makers}->{"Caravans-Wohnm"}    = 15672;
$G_DATA->{AUTOSCOUT}->{makers}->{"Casalini"}          = 16407;
$G_DATA->{AUTOSCOUT}->{makers}->{"Caterham"}          = 16335;
$G_DATA->{AUTOSCOUT}->{makers}->{"Changhe"}           = 16401;
$G_DATA->{AUTOSCOUT}->{makers}->{"Chatenet"}          = 16357;
$G_DATA->{AUTOSCOUT}->{makers}->{"Chery"}             = 16384;
$G_DATA->{AUTOSCOUT}->{makers}->{"Chevrolet"}         = 19;
$G_DATA->{AUTOSCOUT}->{makers}->{"Chrysler"}          = 20;
$G_DATA->{AUTOSCOUT}->{makers}->{"Citroen"}           = 21;
$G_DATA->{AUTOSCOUT}->{makers}->{"CityEL"}            = 16411;
$G_DATA->{AUTOSCOUT}->{makers}->{"CMC"}               = 16406;
$G_DATA->{AUTOSCOUT}->{makers}->{"Corvette"}          = 16380;
$G_DATA->{AUTOSCOUT}->{makers}->{"Courb"}             = 51558;
$G_DATA->{AUTOSCOUT}->{makers}->{"Dacia"}             = 16360;
$G_DATA->{AUTOSCOUT}->{makers}->{"Daewoo"}            = 22;
$G_DATA->{AUTOSCOUT}->{makers}->{"DAF"}               = 16333;
$G_DATA->{AUTOSCOUT}->{makers}->{"Daihatsu"}          = 23;
$G_DATA->{AUTOSCOUT}->{makers}->{"Daimler"}           = 16397;
$G_DATA->{AUTOSCOUT}->{makers}->{"Dangel"}            = 16434;
$G_DATA->{AUTOSCOUT}->{makers}->{"De la Chapelle"}    = 16423;
$G_DATA->{AUTOSCOUT}->{makers}->{"De Tomaso"}         = 51779;
$G_DATA->{AUTOSCOUT}->{makers}->{"Derways"}           = 16391;
$G_DATA->{AUTOSCOUT}->{makers}->{"DFSK"}              = 51773;
$G_DATA->{AUTOSCOUT}->{makers}->{"Dodge"}             = 2152;
$G_DATA->{AUTOSCOUT}->{makers}->{"Donkervoort"}       = 16339;
$G_DATA->{AUTOSCOUT}->{makers}->{"DR Motor"}          = 16383;
$G_DATA->{AUTOSCOUT}->{makers}->{"DS Automobiles"}    = 16415;
$G_DATA->{AUTOSCOUT}->{makers}->{"Dutton"}            = 51552;
$G_DATA->{AUTOSCOUT}->{makers}->{"Estrima"}           = 16436;
$G_DATA->{AUTOSCOUT}->{makers}->{"Ferrari"}           = 27;
$G_DATA->{AUTOSCOUT}->{makers}->{"Fiat"}              = 28;
$G_DATA->{AUTOSCOUT}->{makers}->{"FISKER"}            = 51543;
$G_DATA->{AUTOSCOUT}->{makers}->{"Gac Gonow"}         = 51542;
$G_DATA->{AUTOSCOUT}->{makers}->{"Galloper"}          = 16337;
$G_DATA->{AUTOSCOUT}->{makers}->{"GAZ"}               = 16386;
$G_DATA->{AUTOSCOUT}->{makers}->{"Geely"}             = 16392;
$G_DATA->{AUTOSCOUT}->{makers}->{"GEM"}               = 16403;
$G_DATA->{AUTOSCOUT}->{makers}->{"GEMBALLA"}          = 51540;
$G_DATA->{AUTOSCOUT}->{makers}->{"Giotti Victoria"}   = 16421;
$G_DATA->{AUTOSCOUT}->{makers}->{"GMC"}               = 2153;
$G_DATA->{AUTOSCOUT}->{makers}->{"Great Wall"}        = 16382;
$G_DATA->{AUTOSCOUT}->{makers}->{"Grecav"}            = 16409;
$G_DATA->{AUTOSCOUT}->{makers}->{"Haima"}             = 51512;
$G_DATA->{AUTOSCOUT}->{makers}->{"Hamann"}            = 51534;
$G_DATA->{AUTOSCOUT}->{makers}->{"Honda"}             = 31;
$G_DATA->{AUTOSCOUT}->{makers}->{"HUMMER"}            = 15674;
$G_DATA->{AUTOSCOUT}->{makers}->{"Hurtan"}            = 51767;
$G_DATA->{AUTOSCOUT}->{makers}->{"Hyundai"}           = 33;
$G_DATA->{AUTOSCOUT}->{makers}->{"Infiniti"}          = 16355;
$G_DATA->{AUTOSCOUT}->{makers}->{"Innocenti"}         = 15629;
$G_DATA->{AUTOSCOUT}->{makers}->{"Iso Rivolta"}       = 16402;
$G_DATA->{AUTOSCOUT}->{makers}->{"Isuzu"}             = 35;
$G_DATA->{AUTOSCOUT}->{makers}->{"Iveco"}             = 14882;
$G_DATA->{AUTOSCOUT}->{makers}->{"IZH"}               = 16387;
$G_DATA->{AUTOSCOUT}->{makers}->{"Jaguar"}            = 37;
$G_DATA->{AUTOSCOUT}->{makers}->{"Jeep"}              = 38;
$G_DATA->{AUTOSCOUT}->{makers}->{"Karabag"}           = 16417;
$G_DATA->{AUTOSCOUT}->{makers}->{"Kia"}               = 39;
$G_DATA->{AUTOSCOUT}->{makers}->{"Koenigsegg"}        = 51781;
$G_DATA->{AUTOSCOUT}->{makers}->{"KTM"}               = 50060;
$G_DATA->{AUTOSCOUT}->{makers}->{"Lada"}              = 40;
$G_DATA->{AUTOSCOUT}->{makers}->{"Lamborghini"}       = 41;
$G_DATA->{AUTOSCOUT}->{makers}->{"Lancia"}            = 42;
$G_DATA->{AUTOSCOUT}->{makers}->{"Land Rover"}        = 15641;
$G_DATA->{AUTOSCOUT}->{makers}->{"LDV"}               = 16426;
$G_DATA->{AUTOSCOUT}->{makers}->{"Lexus"}             = 43;
$G_DATA->{AUTOSCOUT}->{makers}->{"Lifan"}             = 16393;
$G_DATA->{AUTOSCOUT}->{makers}->{"Ligier"}            = 16353;
$G_DATA->{AUTOSCOUT}->{makers}->{"Lincoln"}           = 14890;
$G_DATA->{AUTOSCOUT}->{makers}->{"Lotus"}             = 44;
$G_DATA->{AUTOSCOUT}->{makers}->{"Mahindra"}          = 16359;
$G_DATA->{AUTOSCOUT}->{makers}->{"MAN"}               = 51780;
$G_DATA->{AUTOSCOUT}->{makers}->{"Mansory"}           = 16435;
$G_DATA->{AUTOSCOUT}->{makers}->{"Martin Motors"}     = 16410;
$G_DATA->{AUTOSCOUT}->{makers}->{"Maserati"}          = 45;
$G_DATA->{AUTOSCOUT}->{makers}->{"Maybach"}           = 16348;
$G_DATA->{AUTOSCOUT}->{makers}->{"Mazda"}             = 46;
$G_DATA->{AUTOSCOUT}->{makers}->{"McLaren"}           = 51519;
$G_DATA->{AUTOSCOUT}->{makers}->{"Melex"}             = 16399;
$G_DATA->{AUTOSCOUT}->{makers}->{"MG"}                = 48;
$G_DATA->{AUTOSCOUT}->{makers}->{"Microcar"}          = 16361;
$G_DATA->{AUTOSCOUT}->{makers}->{"Minauto"}           = 51766;
$G_DATA->{AUTOSCOUT}->{makers}->{"MINI"}              = 16338;
$G_DATA->{AUTOSCOUT}->{makers}->{"Mitsubishi"}        = 50;
$G_DATA->{AUTOSCOUT}->{makers}->{"Mitsuoka"}          = 51782;
$G_DATA->{AUTOSCOUT}->{makers}->{"Morgan"}            = 51;
$G_DATA->{AUTOSCOUT}->{makers}->{"Moskvich"}          = 16388;
$G_DATA->{AUTOSCOUT}->{makers}->{"MP Lafer"}          = 51554;
$G_DATA->{AUTOSCOUT}->{makers}->{"Nissan"}            = 52;
$G_DATA->{AUTOSCOUT}->{makers}->{"Oldsmobile"}        = 53;
$G_DATA->{AUTOSCOUT}->{makers}->{"Oldtimer"}          = 15670;
$G_DATA->{AUTOSCOUT}->{makers}->{"Pagani"}            = 16341;
$G_DATA->{AUTOSCOUT}->{makers}->{"Panther Westwinds"} = 51553;
$G_DATA->{AUTOSCOUT}->{makers}->{"Peugeot"}           = 55;
$G_DATA->{AUTOSCOUT}->{makers}->{"PGO"}               = 50083;
$G_DATA->{AUTOSCOUT}->{makers}->{"Piaggio"}           = 16350;
$G_DATA->{AUTOSCOUT}->{makers}->{"Plymouth"}          = 51770;
$G_DATA->{AUTOSCOUT}->{makers}->{"Pontiac"}           = 56;
$G_DATA->{AUTOSCOUT}->{makers}->{"Porsche"}           = 57;
$G_DATA->{AUTOSCOUT}->{makers}->{"Proton"}            = 15636;
$G_DATA->{AUTOSCOUT}->{makers}->{"Puch"}              = 51768;
$G_DATA->{AUTOSCOUT}->{makers}->{"Qoros"}             = 16412;
$G_DATA->{AUTOSCOUT}->{makers}->{"Qvale"}             = 16425;
$G_DATA->{AUTOSCOUT}->{makers}->{"Reliant"}           = 16398;
$G_DATA->{AUTOSCOUT}->{makers}->{"Renault"}           = 60;
$G_DATA->{AUTOSCOUT}->{makers}->{"Rolls-Royce"}       = 61;
$G_DATA->{AUTOSCOUT}->{makers}->{"Rover"}             = 62;
$G_DATA->{AUTOSCOUT}->{makers}->{"Ruf"}               = 51536;
$G_DATA->{AUTOSCOUT}->{makers}->{"Saab"}              = 63;
$G_DATA->{AUTOSCOUT}->{makers}->{"Santana"}           = 16369;
$G_DATA->{AUTOSCOUT}->{makers}->{"Savel"}             = 16405;
$G_DATA->{AUTOSCOUT}->{makers}->{"SDG"}               = 51771;
$G_DATA->{AUTOSCOUT}->{makers}->{"SEAT"}              = 64;
$G_DATA->{AUTOSCOUT}->{makers}->{"Skoda"}             = 65;
$G_DATA->{AUTOSCOUT}->{makers}->{"smart"}             = 15525;
$G_DATA->{AUTOSCOUT}->{makers}->{"SpeedArt"}          = 51538;
$G_DATA->{AUTOSCOUT}->{makers}->{"Spyker"}            = 16377;
$G_DATA->{AUTOSCOUT}->{makers}->{"SsangYong"}         = 66;
$G_DATA->{AUTOSCOUT}->{makers}->{"Subaru"}            = 67;
$G_DATA->{AUTOSCOUT}->{makers}->{"Suzuki"}            = 68;
$G_DATA->{AUTOSCOUT}->{makers}->{"TagAZ"}             = 16395;
$G_DATA->{AUTOSCOUT}->{makers}->{"Talbot"}            = 51551;
$G_DATA->{AUTOSCOUT}->{makers}->{"Tasso"}             = 16404;
$G_DATA->{AUTOSCOUT}->{makers}->{"Tata"}              = 16327;
$G_DATA->{AUTOSCOUT}->{makers}->{"Tazzari EV"}        = 51557;
$G_DATA->{AUTOSCOUT}->{makers}->{"TECHART"}           = 51535;
$G_DATA->{AUTOSCOUT}->{makers}->{"Tesla"}             = 51520;
$G_DATA->{AUTOSCOUT}->{makers}->{"Town Life"}         = 16420;
$G_DATA->{AUTOSCOUT}->{makers}->{"Toyota"}            = 70;
$G_DATA->{AUTOSCOUT}->{makers}->{"Trabant"}           = 15633;
$G_DATA->{AUTOSCOUT}->{makers}->{"Trailer-Anhaenger"} = 16326;
$G_DATA->{AUTOSCOUT}->{makers}->{"Triumph"}           = 2120;
$G_DATA->{AUTOSCOUT}->{makers}->{"Trucks-Lkw"}        = 16253;
$G_DATA->{AUTOSCOUT}->{makers}->{"TVR"}               = 71;
$G_DATA->{AUTOSCOUT}->{makers}->{"UAZ"}               = 16389;
$G_DATA->{AUTOSCOUT}->{makers}->{"VAZ"}               = 16385;
$G_DATA->{AUTOSCOUT}->{makers}->{"VEM"}               = 16422;
$G_DATA->{AUTOSCOUT}->{makers}->{"Volvo"}             = 73;
$G_DATA->{AUTOSCOUT}->{makers}->{"Vortex"}            = 51514;
$G_DATA->{AUTOSCOUT}->{makers}->{"Wallys"}            = 51776;
$G_DATA->{AUTOSCOUT}->{makers}->{"Wartburg"}          = 16336;
$G_DATA->{AUTOSCOUT}->{makers}->{"Westfield"}         = 51513;
$G_DATA->{AUTOSCOUT}->{makers}->{"Wiesmann"}          = 16351;
$G_DATA->{AUTOSCOUT}->{makers}->{"Zastava"}           = 16408;
$G_DATA->{AUTOSCOUT}->{makers}->{"ZAZ"}               = 16394;
$G_DATA->{AUTOSCOUT}->{makers}->{"Sonstige"}          = 16328;
